package com.ws.application

import com.ws.beans.TestCondition

class Test {

	static main(args) {
		
		
		def response="""

<?xml version="1.0" encoding="utf-8"?>
<string xmlns="http://www.webserviceX.NET">&lt;NewDataSet&gt;
  &lt;Table&gt;
    &lt;AirportCode&gt;TRR&lt;/AirportCode&gt;
    &lt;CityOrAirportName&gt;TRINCOMALEE CHINA BAY&lt;/CityOrAirportName&gt;
    &lt;Country&gt;Sri Lanka&lt;/Country&gt;
    &lt;CountryAbbrviation&gt;LK&lt;/CountryAbbrviation&gt;
    &lt;CountryCode&gt;711&lt;/CountryCode&gt;
    &lt;GMTOffset&gt;5.5&lt;/GMTOffset&gt;
    &lt;RunwayLengthFeet&gt;7150&lt;/RunwayLengthFeet&gt;
    &lt;RunwayElevationFeet&gt;6&lt;/RunwayElevationFeet&gt;
    &lt;LatitudeDegree&gt;8&lt;/LatitudeDegree&gt;
    &lt;LatitudeMinute&gt;32&lt;/LatitudeMinute&gt;
    &lt;LatitudeSecond&gt;0&lt;/LatitudeSecond&gt;
    &lt;LatitudeNpeerS&gt;N&lt;/LatitudeNpeerS&gt;
    &lt;LongitudeDegree&gt;81&lt;/LongitudeDegree&gt;
    &lt;LongitudeMinute&gt;11&lt;/LongitudeMinute&gt;
    &lt;LongitudeSeconds&gt;0&lt;/LongitudeSeconds&gt;
    &lt;LongitudeEperW&gt;E&lt;/LongitudeEperW&gt;
  &lt;/Table&gt;
  &lt;Table&gt;
    &lt;AirportCode&gt;TRR&lt;/AirportCode&gt;
    &lt;CityOrAirportName&gt;TRINCOMALEE CHINA BAY&lt;/CityOrAirportName&gt;
    &lt;Country&gt;Sri Lanka&lt;/Country&gt;
    &lt;CountryAbbrviation&gt;LK&lt;/CountryAbbrviation&gt;
    &lt;CountryCode&gt;711&lt;/CountryCode&gt;
    &lt;GMTOffset&gt;5.5&lt;/GMTOffset&gt;
    &lt;RunwayLengthFeet&gt;7150&lt;/RunwayLengthFeet&gt;
    &lt;RunwayElevationFeet&gt;6&lt;/RunwayElevationFeet&gt;
    &lt;LatitudeDegree&gt;8&lt;/LatitudeDegree&gt;
    &lt;LatitudeMinute&gt;32&lt;/LatitudeMinute&gt;
    &lt;LatitudeSecond&gt;0&lt;/LatitudeSecond&gt;
    &lt;LatitudeNpeerS&gt;N&lt;/LatitudeNpeerS&gt;
    &lt;LongitudeDegree&gt;81&lt;/LongitudeDegree&gt;
    &lt;LongitudeMinute&gt;11&lt;/LongitudeMinute&gt;
    &lt;LongitudeSeconds&gt;0&lt;/LongitudeSeconds&gt;
    &lt;LongitudeEperW&gt;E&lt;/LongitudeEperW&gt;
  &lt;/Table&gt;
  &lt;Table&gt;
    &lt;AirportCode&gt;ADP&lt;/AirportCode&gt;
    &lt;CityOrAirportName&gt;ANURADHAPURA&lt;/CityOrAirportName&gt;
    &lt;Country&gt;Sri Lanka&lt;/Country&gt;
    &lt;CountryAbbrviation&gt;LK&lt;/CountryAbbrviation&gt;
    &lt;CountryCode&gt;711&lt;/CountryCode&gt;
    &lt;GMTOffset&gt;-5.5&lt;/GMTOffset&gt;
    &lt;RunwayLengthFeet&gt;4000&lt;/RunwayLengthFeet&gt;
    &lt;RunwayElevationFeet&gt;324&lt;/RunwayElevationFeet&gt;
    &lt;LatitudeDegree&gt;8&lt;/LatitudeDegree&gt;
    &lt;LatitudeMinute&gt;18&lt;/LatitudeMinute&gt;
    &lt;LatitudeSecond&gt;0&lt;/LatitudeSecond&gt;
    &lt;LatitudeNpeerS&gt;N&lt;/LatitudeNpeerS&gt;
    &lt;LongitudeDegree&gt;80&lt;/LongitudeDegree&gt;
    &lt;LongitudeMinute&gt;25&lt;/LongitudeMinute&gt;
    &lt;LongitudeSeconds&gt;0&lt;/LongitudeSeconds&gt;
    &lt;LongitudeEperW&gt;E&lt;/LongitudeEperW&gt;
  &lt;/Table&gt;
  &lt;Table&gt;
    &lt;AirportCode&gt;ADP&lt;/AirportCode&gt;
    &lt;CityOrAirportName&gt;ANURADHAPURA&lt;/CityOrAirportName&gt;
    &lt;Country&gt;Sri Lanka&lt;/Country&gt;
    &lt;CountryAbbrviation&gt;LK&lt;/CountryAbbrviation&gt;
    &lt;CountryCode&gt;711&lt;/CountryCode&gt;
    &lt;GMTOffset&gt;-5.5&lt;/GMTOffset&gt;
    &lt;RunwayLengthFeet&gt;4000&lt;/RunwayLengthFeet&gt;
    &lt;RunwayElevationFeet&gt;324&lt;/RunwayElevationFeet&gt;
    &lt;LatitudeDegree&gt;8&lt;/LatitudeDegree&gt;
    &lt;LatitudeMinute&gt;18&lt;/LatitudeMinute&gt;
    &lt;LatitudeSecond&gt;0&lt;/LatitudeSecond&gt;
    &lt;LatitudeNpeerS&gt;N&lt;/LatitudeNpeerS&gt;
    &lt;LongitudeDegree&gt;80&lt;/LongitudeDegree&gt;
    &lt;LongitudeMinute&gt;25&lt;/LongitudeMinute&gt;
    &lt;LongitudeSeconds&gt;0&lt;/LongitudeSeconds&gt;
    &lt;LongitudeEperW&gt;E&lt;/LongitudeEperW&gt;
  &lt;/Table&gt;
  &lt;Table&gt;
    &lt;AirportCode&gt;GOY&lt;/AirportCode&gt;
    &lt;CityOrAirportName&gt;GAL OYA AMPARAI&lt;/CityOrAirportName&gt;
    &lt;Country&gt;Sri Lanka&lt;/Country&gt;
    &lt;CountryAbbrviation&gt;LK&lt;/CountryAbbrviation&gt;
    &lt;CountryCode&gt;711&lt;/CountryCode&gt;
    &lt;GMTOffset&gt;-5.5&lt;/GMTOffset&gt;
    &lt;RunwayLengthFeet&gt;3600&lt;/RunwayLengthFeet&gt;
    &lt;RunwayElevationFeet&gt;150&lt;/RunwayElevationFeet&gt;
    &lt;LatitudeDegree&gt;7&lt;/LatitudeDegree&gt;
    &lt;LatitudeMinute&gt;20&lt;/LatitudeMinute&gt;
    &lt;LatitudeSecond&gt;0&lt;/LatitudeSecond&gt;
    &lt;LatitudeNpeerS&gt;N&lt;/LatitudeNpeerS&gt;
    &lt;LongitudeDegree&gt;81&lt;/LongitudeDegree&gt;
    &lt;LongitudeMinute&gt;37&lt;/LongitudeMinute&gt;
    &lt;LongitudeSeconds&gt;0&lt;/LongitudeSeconds&gt;
    &lt;LongitudeEperW&gt;E&lt;/LongitudeEperW&gt;
  &lt;/Table&gt;
  &lt;Table&gt;
    &lt;AirportCode&gt;GOY&lt;/AirportCode&gt;
    &lt;CityOrAirportName&gt;GAL OYA AMPARAI&lt;/CityOrAirportName&gt;
    &lt;Country&gt;Sri Lanka&lt;/Country&gt;
    &lt;CountryAbbrviation&gt;LK&lt;/CountryAbbrviation&gt;
    &lt;CountryCode&gt;711&lt;/CountryCode&gt;
    &lt;GMTOffset&gt;-5.5&lt;/GMTOffset&gt;
    &lt;RunwayLengthFeet&gt;3600&lt;/RunwayLengthFeet&gt;
    &lt;RunwayElevationFeet&gt;150&lt;/RunwayElevationFeet&gt;
    &lt;LatitudeDegree&gt;7&lt;/LatitudeDegree&gt;
    &lt;LatitudeMinute&gt;20&lt;/LatitudeMinute&gt;
    &lt;LatitudeSecond&gt;0&lt;/LatitudeSecond&gt;
    &lt;LatitudeNpeerS&gt;N&lt;/LatitudeNpeerS&gt;
    &lt;LongitudeDegree&gt;81&lt;/LongitudeDegree&gt;
    &lt;LongitudeMinute&gt;37&lt;/LongitudeMinute&gt;
    &lt;LongitudeSeconds&gt;0&lt;/LongitudeSeconds&gt;
    &lt;LongitudeEperW&gt;E&lt;/LongitudeEperW&gt;
  &lt;/Table&gt;
  &lt;Table&gt;
    &lt;AirportCode&gt;BTC&lt;/AirportCode&gt;
    &lt;CityOrAirportName&gt;BATTICALOA&lt;/CityOrAirportName&gt;
    &lt;Country&gt;Sri Lanka&lt;/Country&gt;
    &lt;CountryAbbrviation&gt;LK&lt;/CountryAbbrviation&gt;
    &lt;CountryCode&gt;711&lt;/CountryCode&gt;
    &lt;GMTOffset&gt;-5.5&lt;/GMTOffset&gt;
    &lt;RunwayLengthFeet&gt;3500&lt;/RunwayLengthFeet&gt;
    &lt;RunwayElevationFeet&gt;10&lt;/RunwayElevationFeet&gt;
    &lt;LatitudeDegree&gt;7&lt;/LatitudeDegree&gt;
    &lt;LatitudeMinute&gt;42&lt;/LatitudeMinute&gt;
    &lt;LatitudeSecond&gt;0&lt;/LatitudeSecond&gt;
    &lt;LatitudeNpeerS&gt;N&lt;/LatitudeNpeerS&gt;
    &lt;LongitudeDegree&gt;81&lt;/LongitudeDegree&gt;
    &lt;LongitudeMinute&gt;40&lt;/LongitudeMinute&gt;
    &lt;LongitudeSeconds&gt;0&lt;/LongitudeSeconds&gt;
    &lt;LongitudeEperW&gt;E&lt;/LongitudeEperW&gt;
  &lt;/Table&gt;
  &lt;Table&gt;
    &lt;AirportCode&gt;BTC&lt;/AirportCode&gt;
    &lt;CityOrAirportName&gt;BATTICALOA&lt;/CityOrAirportName&gt;
    &lt;Country&gt;Sri Lanka&lt;/Country&gt;
    &lt;CountryAbbrviation&gt;LK&lt;/CountryAbbrviation&gt;
    &lt;CountryCode&gt;711&lt;/CountryCode&gt;
    &lt;GMTOffset&gt;-5.5&lt;/GMTOffset&gt;
    &lt;RunwayLengthFeet&gt;3500&lt;/RunwayLengthFeet&gt;
    &lt;RunwayElevationFeet&gt;10&lt;/RunwayElevationFeet&gt;
    &lt;LatitudeDegree&gt;7&lt;/LatitudeDegree&gt;
    &lt;LatitudeMinute&gt;42&lt;/LatitudeMinute&gt;
    &lt;LatitudeSecond&gt;0&lt;/LatitudeSecond&gt;
    &lt;LatitudeNpeerS&gt;N&lt;/LatitudeNpeerS&gt;
    &lt;LongitudeDegree&gt;81&lt;/LongitudeDegree&gt;
    &lt;LongitudeMinute&gt;40&lt;/LongitudeMinute&gt;
    &lt;LongitudeSeconds&gt;0&lt;/LongitudeSeconds&gt;
    &lt;LongitudeEperW&gt;E&lt;/LongitudeEperW&gt;
  &lt;/Table&gt;
  &lt;Table&gt;
    &lt;AirportCode&gt;MNH&lt;/AirportCode&gt;
    &lt;CityOrAirportName&gt;MINNERIYA&lt;/CityOrAirportName&gt;
    &lt;Country&gt;Sri Lanka&lt;/Country&gt;
    &lt;CountryAbbrviation&gt;LK&lt;/CountryAbbrviation&gt;
    &lt;CountryCode&gt;711&lt;/CountryCode&gt;
    &lt;GMTOffset&gt;-5.5&lt;/GMTOffset&gt;
    &lt;RunwayLengthFeet&gt;7500&lt;/RunwayLengthFeet&gt;
    &lt;RunwayElevationFeet&gt;165&lt;/RunwayElevationFeet&gt;
    &lt;LatitudeDegree&gt;7&lt;/LatitudeDegree&gt;
    &lt;LatitudeMinute&gt;45&lt;/LatitudeMinute&gt;
    &lt;LatitudeSecond&gt;0&lt;/LatitudeSecond&gt;
    &lt;LatitudeNpeerS&gt;N&lt;/LatitudeNpeerS&gt;
    &lt;LongitudeDegree&gt;83&lt;/LongitudeDegree&gt;
    &lt;LongitudeMinute&gt;0&lt;/LongitudeMinute&gt;
    &lt;LongitudeSeconds&gt;0&lt;/LongitudeSeconds&gt;
    &lt;LongitudeEperW&gt;E&lt;/LongitudeEperW&gt;
  &lt;/Table&gt;
  &lt;Table&gt;
    &lt;AirportCode&gt;MNH&lt;/AirportCode&gt;
    &lt;CityOrAirportName&gt;MINNERIYA&lt;/CityOrAirportName&gt;
    &lt;Country&gt;Sri Lanka&lt;/Country&gt;
    &lt;CountryAbbrviation&gt;LK&lt;/CountryAbbrviation&gt;
    &lt;CountryCode&gt;711&lt;/CountryCode&gt;
    &lt;GMTOffset&gt;-5.5&lt;/GMTOffset&gt;
    &lt;RunwayLengthFeet&gt;7500&lt;/RunwayLengthFeet&gt;
    &lt;RunwayElevationFeet&gt;165&lt;/RunwayElevationFeet&gt;
    &lt;LatitudeDegree&gt;7&lt;/LatitudeDegree&gt;
    &lt;LatitudeMinute&gt;45&lt;/LatitudeMinute&gt;
    &lt;LatitudeSecond&gt;0&lt;/LatitudeSecond&gt;
    &lt;LatitudeNpeerS&gt;N&lt;/LatitudeNpeerS&gt;
    &lt;LongitudeDegree&gt;83&lt;/LongitudeDegree&gt;
    &lt;LongitudeMinute&gt;0&lt;/LongitudeMinute&gt;
    &lt;LongitudeSeconds&gt;0&lt;/LongitudeSeconds&gt;
    &lt;LongitudeEperW&gt;E&lt;/LongitudeEperW&gt;
  &lt;/Table&gt;
  &lt;Table&gt;
    &lt;AirportCode&gt;RML&lt;/AirportCode&gt;
    &lt;CityOrAirportName&gt;COLOMBO RATMALANA&lt;/CityOrAirportName&gt;
    &lt;Country&gt;Sri Lanka&lt;/Country&gt;
    &lt;CountryAbbrviation&gt;LK&lt;/CountryAbbrviation&gt;
    &lt;CountryCode&gt;711&lt;/CountryCode&gt;
    &lt;RunwayLengthFeet&gt;0&lt;/RunwayLengthFeet&gt;
    &lt;RunwayElevationFeet&gt;0&lt;/RunwayElevationFeet&gt;
    &lt;LatitudeDegree&gt;0&lt;/LatitudeDegree&gt;
    &lt;LatitudeMinute&gt;0&lt;/LatitudeMinute&gt;
    &lt;LatitudeSecond&gt;0&lt;/LatitudeSecond&gt;
    &lt;LatitudeNpeerS&gt;S&lt;/LatitudeNpeerS&gt;
    &lt;LongitudeDegree&gt;0&lt;/LongitudeDegree&gt;
    &lt;LongitudeMinute&gt;0&lt;/LongitudeMinute&gt;
    &lt;LongitudeSeconds&gt;0&lt;/LongitudeSeconds&gt;
    &lt;LongitudeEperW&gt;W&lt;/LongitudeEperW&gt;
  &lt;/Table&gt;
  &lt;Table&gt;
    &lt;AirportCode&gt;RML&lt;/AirportCode&gt;
    &lt;CityOrAirportName&gt;COLOMBO RATMALANA&lt;/CityOrAirportName&gt;
    &lt;Country&gt;Sri Lanka&lt;/Country&gt;
    &lt;CountryAbbrviation&gt;LK&lt;/CountryAbbrviation&gt;
    &lt;CountryCode&gt;711&lt;/CountryCode&gt;
    &lt;RunwayLengthFeet&gt;0&lt;/RunwayLengthFeet&gt;
    &lt;RunwayElevationFeet&gt;0&lt;/RunwayElevationFeet&gt;
    &lt;LatitudeDegree&gt;0&lt;/LatitudeDegree&gt;
    &lt;LatitudeMinute&gt;0&lt;/LatitudeMinute&gt;
    &lt;LatitudeSecond&gt;0&lt;/LatitudeSecond&gt;
    &lt;LatitudeNpeerS&gt;S&lt;/LatitudeNpeerS&gt;
    &lt;LongitudeDegree&gt;0&lt;/LongitudeDegree&gt;
    &lt;LongitudeMinute&gt;0&lt;/LongitudeMinute&gt;
    &lt;LongitudeSeconds&gt;0&lt;/LongitudeSeconds&gt;
    &lt;LongitudeEperW&gt;W&lt;/LongitudeEperW&gt;
  &lt;/Table&gt;
  &lt;Table&gt;
    &lt;AirportCode&gt;JAF&lt;/AirportCode&gt;
    &lt;CityOrAirportName&gt;JAFFNA KANKESANTU&lt;/CityOrAirportName&gt;
    &lt;Country&gt;Sri Lanka&lt;/Country&gt;
    &lt;CountryAbbrviation&gt;LK&lt;/CountryAbbrviation&gt;
    &lt;CountryCode&gt;711&lt;/CountryCode&gt;
    &lt;GMTOffset&gt;-5.5&lt;/GMTOffset&gt;
    &lt;RunwayLengthFeet&gt;7500&lt;/RunwayLengthFeet&gt;
    &lt;RunwayElevationFeet&gt;33&lt;/RunwayElevationFeet&gt;
    &lt;LatitudeDegree&gt;9&lt;/LatitudeDegree&gt;
    &lt;LatitudeMinute&gt;47&lt;/LatitudeMinute&gt;
    &lt;LatitudeSecond&gt;0&lt;/LatitudeSecond&gt;
    &lt;LatitudeNpeerS&gt;N&lt;/LatitudeNpeerS&gt;
    &lt;LongitudeDegree&gt;80&lt;/LongitudeDegree&gt;
    &lt;LongitudeMinute&gt;4&lt;/LongitudeMinute&gt;
    &lt;LongitudeSeconds&gt;0&lt;/LongitudeSeconds&gt;
    &lt;LongitudeEperW&gt;E&lt;/LongitudeEperW&gt;
  &lt;/Table&gt;
  &lt;Table&gt;
    &lt;AirportCode&gt;JAF&lt;/AirportCode&gt;
    &lt;CityOrAirportName&gt;JAFFNA KANKESANTU&lt;/CityOrAirportName&gt;
    &lt;Country&gt;Sri Lanka&lt;/Country&gt;
    &lt;CountryAbbrviation&gt;LK&lt;/CountryAbbrviation&gt;
    &lt;CountryCode&gt;711&lt;/CountryCode&gt;
    &lt;GMTOffset&gt;-5.5&lt;/GMTOffset&gt;
    &lt;RunwayLengthFeet&gt;7500&lt;/RunwayLengthFeet&gt;
    &lt;RunwayElevationFeet&gt;33&lt;/RunwayElevationFeet&gt;
    &lt;LatitudeDegree&gt;9&lt;/LatitudeDegree&gt;
    &lt;LatitudeMinute&gt;47&lt;/LatitudeMinute&gt;
    &lt;LatitudeSecond&gt;0&lt;/LatitudeSecond&gt;
    &lt;LatitudeNpeerS&gt;N&lt;/LatitudeNpeerS&gt;
    &lt;LongitudeDegree&gt;80&lt;/LongitudeDegree&gt;
    &lt;LongitudeMinute&gt;4&lt;/LongitudeMinute&gt;
    &lt;LongitudeSeconds&gt;0&lt;/LongitudeSeconds&gt;
    &lt;LongitudeEperW&gt;E&lt;/LongitudeEperW&gt;
  &lt;/Table&gt;
  &lt;Table&gt;
    &lt;AirportCode&gt;CMB&lt;/AirportCode&gt;
    &lt;CityOrAirportName&gt;COLOMBO KATUNAYAKE&lt;/CityOrAirportName&gt;
    &lt;Country&gt;Sri Lanka&lt;/Country&gt;
    &lt;CountryAbbrviation&gt;LK&lt;/CountryAbbrviation&gt;
    &lt;CountryCode&gt;711&lt;/CountryCode&gt;
    &lt;GMTOffset&gt;-5.5&lt;/GMTOffset&gt;
    &lt;RunwayLengthFeet&gt;11050&lt;/RunwayLengthFeet&gt;
    &lt;RunwayElevationFeet&gt;29&lt;/RunwayElevationFeet&gt;
    &lt;LatitudeDegree&gt;6&lt;/LatitudeDegree&gt;
    &lt;LatitudeMinute&gt;56&lt;/LatitudeMinute&gt;
    &lt;LatitudeSecond&gt;0&lt;/LatitudeSecond&gt;
    &lt;LatitudeNpeerS&gt;N&lt;/LatitudeNpeerS&gt;
    &lt;LongitudeDegree&gt;79&lt;/LongitudeDegree&gt;
    &lt;LongitudeMinute&gt;51&lt;/LongitudeMinute&gt;
    &lt;LongitudeSeconds&gt;0&lt;/LongitudeSeconds&gt;
    &lt;LongitudeEperW&gt;E&lt;/LongitudeEperW&gt;
  &lt;/Table&gt;
  &lt;Table&gt;
    &lt;AirportCode&gt;CMB&lt;/AirportCode&gt;
    &lt;CityOrAirportName&gt;COLOMBO KATUNAYAKE&lt;/CityOrAirportName&gt;
    &lt;Country&gt;Sri Lanka&lt;/Country&gt;
    &lt;CountryAbbrviation&gt;LK&lt;/CountryAbbrviation&gt;
    &lt;CountryCode&gt;711&lt;/CountryCode&gt;
    &lt;GMTOffset&gt;-5.5&lt;/GMTOffset&gt;
    &lt;RunwayLengthFeet&gt;11050&lt;/RunwayLengthFeet&gt;
    &lt;RunwayElevationFeet&gt;29&lt;/RunwayElevationFeet&gt;
    &lt;LatitudeDegree&gt;6&lt;/LatitudeDegree&gt;
    &lt;LatitudeMinute&gt;56&lt;/LatitudeMinute&gt;
    &lt;LatitudeSecond&gt;0&lt;/LatitudeSecond&gt;
    &lt;LatitudeNpeerS&gt;N&lt;/LatitudeNpeerS&gt;
    &lt;LongitudeDegree&gt;79&lt;/LongitudeDegree&gt;
    &lt;LongitudeMinute&gt;51&lt;/LongitudeMinute&gt;
    &lt;LongitudeSeconds&gt;0&lt;/LongitudeSeconds&gt;
    &lt;LongitudeEperW&gt;E&lt;/LongitudeEperW&gt;
  &lt;/Table&gt;
&lt;/NewDataSet&gt;</string>
"""
		TestWebservice tw=new TestWebservice();
		TestCondition cond= new TestCondition(
			 positive:true,
			condition : "MINNERIYA"
			);
		println (tw.verify(response,cond))

		
			}
	
}
